ALTER TABLE Users
	DROP CONSTRAINT PK_UsersTable

ALTER TABLE Users
	ADD CONSTRAINT PK_UsersTable PRIMARY KEY(Id)
	
ALTER TABLE Users
	ADD CONSTRAINT UC_UserName UNIQUE (Username)

ALTER TABLE Users
	ADD CONSTRAINT CHK_Usernamelength CHECK (LEN(Username) >= 3)